DROP TABLE PARTIDO CASCADE CONSTRAINTS;
DROP TABLE PARTICIPACION CASCADE CONSTRAINTS;
DROP TABLE OTROS_NOMBRES_EQUIPO CASCADE CONSTRAINTS;
DROP TABLE EQUIPO CASCADE CONSTRAINTS;
DROP TABLE ESTADIO CASCADE CONSTRAINTS;
DROP TABLE DIVISION CASCADE CONSTRAINTS;

DROP SEQUENCE seq_estadio;